### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Tom32i** [Tom32i/synchroplayer#2]
## TODO
- [ ] Prévoir la fine de la video (on stop)
- [ ] Barre de chargement pour la video
- [ ] Control du volume

## Nice to have
- [ ] Local storage remember
- [ ] Partage des sous-titres
- [ ] Télécommande / support mobile
- [ ] notifier des actions des gens ?
